[package]
name = "islefall-server"
description = "The Islefall lockstep relay server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
islefall-net = { path = "../islefall-net", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
